<a href="https://colab.research.google.com/github/nalawneh/jupyter-notebook/blob/main/Udacity_Session_6_%2C_AWS_AI_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/drive/1_56Y9ftnyetjRxWeMU3gqA4u3IIDHhTN?usp=sharing

Python for data analysis book: https://github.com/wesm/pydata-book/blob/3rd-edition/ch10.ipynb

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from pandas import Series, DataFrame

# Series

In [ ]:
obj = pd.Series([4, 7, -5, 3])
print( obj )

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj[0]

np.int64(4)

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.to_list()

[4, 7, -5, 3]

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
print( obj.index )

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c", ] )
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
print( obj2.index)

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
print( obj2["a"] )

-5

In [ ]:
obj2["d"] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2[ ["c", "a", "d"] ]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [ ]:
obj2[ obj2 > 0 ]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
obj2.pow(2)

d    36
b    49
a    25
c     9
dtype: int64

In [ ]:
np.power( obj2 , 2)

d    36
b    49
a    25
c     9
dtype: int64

In [ ]:
print( "b" in obj2.index )
print( "e" in obj2.index )
print()
print( "b" in obj2.values )
print( "e" in obj2.values )

True
False

False
False

In [ ]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj3.to_

In [ ]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
obj3.values

In [ ]:
obj3.index

In [ ]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index= states )
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4[ obj4.notna() ]

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

In [ ]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj4[ obj4.isna() ]

California   NaN
dtype: float64

In [ ]:
print( obj3 )
print()
print( obj4 )

In [ ]:
obj3 + obj4

In [ ]:
obj4.name = "population"
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:

obj4.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj4

# Break

# DataFrames

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
        }
frame = pd.DataFrame(data)

In [ ]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.head(2)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [ ]:
frame.tail(2)

    state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
pd.DataFrame(data, columns=["year", "state"] )

   year   state
0  2000    Ohio
1  2001    Ohio
2  2002    Ohio
3  2001  Nevada
4  2002  Nevada
5  2003  Nevada

In [ ]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [ ]:
print( frame2.columns )

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [ ]:
frame2.state

In [ ]:
print(type( frame2["state"] ))

<class 'pandas.core.series.Series'>

In [ ]:
frame2

In [ ]:
frame2.index

In [ ]:
frame2["pop"][2]

In [ ]:
print( frame2.loc[1])
print()
print( frame2.loc[1,"state"])
print()
print( frame2.iloc[1])
print()
print( frame2.iloc[1 , 1])

In [ ]:
print( frame2.loc[1,:])
print()
print( frame2.iloc[:, 1])

In [ ]:
val = pd.DataFrame([-1.2, -1.5, -1.7], index=["two", "four", "five"])
val.head()

In [ ]:
print( val.loc['two'] )
print()
print( val.iloc[0])

In [ ]:
frame2

In [ ]:
frame2["state"] == "Ohio"

In [ ]:
frame2[ frame2["state"] == "Ohio" ]

In [ ]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

In [ ]:
frame2.drop( columns=['eastern'] )

In [ ]:
frame2

In [ ]:
del frame2["eastern"]
print( frame2.columns)

In [ ]:
frame2

In [ ]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}
               }

In [ ]:
frame3 = pd.DataFrame(populations)
frame3

In [ ]:
frame3.dropna()

In [ ]:
frame3.fillna("MISSING")

In [ ]:
frame3.T

In [ ]:
tmp= frame3.T

In [ ]:
tmp

In [ ]:
tmp.loc[2000]

In [ ]:
tmp[2000]

In [ ]:
tmp["2000"]

In [ ]:
tmp.columns

In [ ]:
tmp.index

In [ ]:
populations

In [ ]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

In [ ]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

In [ ]:
print( frame3.to_numpy())

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

using string indexing gives you the columns

In [ ]:
data["two"]

In [ ]:
data[["three", "one"]]

using numerical indexing gives you the rows

In [ ]:
data[:2]

In [ ]:
data.head()

In [ ]:
data[ data["three"] > 5 ]

In [ ]:
data < 5

In [ ]:
data[data < 5] = 0
data

In [ ]:
data

In [ ]:
data.loc[["Colorado", "New York"]]

In [ ]:
data.loc["Colorado", ["two", "three"]]

In [ ]:
data

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[2, [3, 0, 1]]

In [ ]:
tmp

In [ ]:
tmp.to_csv("tmp.csv")

In [ ]:
tmp.to_excel("tmp.xlsx")

In [ ]:
tmp.to_

In [ ]:
tmp

In [ ]:
tmp

In [ ]:
tmp.iloc[0].plot()

In [ ]:
tmp.iloc[0].hist()

# For extra Info follow:
https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html

# Activity
### Solve the excercises found here : https://www.w3schools.com/python/pandas/exercise.asp?filename=exercise_series1